export const aliases = [
  { value: 'kvartira-ili-dolya-moskva-1', name: 'Квартира или доля' },
  { value: 'zagorodnaya-nedvizhimost', name: 'Загородная недвижимость' },
  { value: 'novostrojka', name: 'Новостройка' },
  { value: 'vtorichnoe-zhile-msk', name: 'Вторичное жилье' },
  {
    value: 'gotovoe-zhile-pri-pokupke-kvartiry-na-domklik',
    name: 'Готовое жилье (покупка на ДомКлик)',
  },
  { value: 'novostroyka', name: 'Новостройка' },
  { value: 'apartamenty', name: 'Апартаменты' },
  { value: 'celevoy', name: 'Целевая' },
  { value: 'komnata', name: 'Комната' },
  { value: 'na-pervonachalnyj-vznos', name: 'На первоначальный взнос' },
  { value: 'gotoviy-dom', name: 'Готовый дом' },
  { value: 'na-novostroyku', name: 'На новостройку' },
  { value: 'novostroyka-msk', name: 'Новостройка' },
  {
    value: 'priobretenie-nedvizhimosti-gotovoe-msk-i-s-p',
    name: 'Приобретение недвижимости',
  },
  { value: 'vtorichnoe-zhile', name: 'Вторичное жилье' },
  { value: 'na-gotovoe-zhile', name: 'На вторичное жилье' },
  { value: 'na-stroyashcheesya-zhile', name: 'На новостройку' },
  { value: 'novosely', name: 'На вторичное жилье' },
  { value: 'zhilaja-nedvizhimost', name: 'Жилая недвижимость' },
  { value: 'zhilishhnaja-pervichnyj-i-vtorichnyj-rynok-zhilja', name: 'Жилищная' },
  { value: 'zalogovaja-nedvizhimost', name: 'Залоговая недвижимость' },
  {
    value: 'pokupka-zhilja-na-vtorichnom-rynke',
    name: 'Недвижимость на вторичном рынке',
  },
  {
    value: 'novostrojka-materinskij-kapital',
    name: 'Новостройка + Материнский капитал',
  },
  { value: 'perspektiva-region', name: 'Перспектива' },
  { value: 'kvartira-materinskij-kapital', name: 'Квартира + Материнский капитал' },
  {
    value: 'pokupka-prodazha-ipotechnoy-kvartiry',
    name: 'Покупка или продажа ипотечной квартиры',
  },
  { value: 'megapolis-region', name: 'Мегаполис' },
  { value: 'bolshe-metrov-nizhe-stavka', name: 'Больше метров-ниже ставка' },
  { value: 'ipotechnyye-kanikuly', name: 'Ипотечные каникулы' },
  { value: 'komfort', name: 'Комфорт' },
  { value: 'ak-bars-biznes', name: 'Ак Барс — Бизнес' },
  { value: 'individualnyy-zhiloy-dom', name: 'Индивидуальный жилой дом' },
  { value: 'stroyazheesya-zhile', name: 'Строящееся жилье' },
  { value: 'gotovoezhile', name: 'Готовое жилье' },
  { value: 'kvartira-na-vtorichnom-rinke', name: 'Квартира на вторичном рынке' },
  { value: 'garazh-mashino-mesto', name: 'Гараж/ машино-место' },
  { value: 'stroitelstvo-zhilogo-doma', name: 'Строительство жилого дома' },
  { value: 'zagorodnyj-dom', name: 'Загородный дом' },
  { value: 'pod-zalog-nedvizhimosti', name: 'Под залог недвижимости' },
  { value: 'nezhilaya-nedvizhimost', name: 'Нежилая недвижимость' },
  { value: 'udobnyy', name: 'Удобный кредит' },
];
